name: Test Build

on:
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: [self-hosted, Linux, X64, ubuntu-latest-lts]

    steps:
      - uses: actions/checkout@v4

      - name: Load NVM and Node
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use node

      - name: Source environment variables
        run: |
          sudo cp /srv/portfolio/.env ./
          sed -i 's/^PORT=.*/PORT=3300/' .env
          source .env

      - name: Install pnpm
        run: sudo npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
