name: Test Build

on:
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: [self-hosted, Linux, X64, ubuntu-latest-lts]

    steps:
      - uses: actions/checkout@v4

      - name: Set PATH for pipx binaries
        run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Load NVM and Node
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use node

      - name: Source environment variables
        run: source /srv/portfolio/.env

      - name: Install pnpm
        run: sudo npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
