name: Test Build

on:
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: [self-hosted, Linux, X64, ubuntu-latest-lts]

    steps:
      - uses: actions/checkout@v4

      - name: Set PATH for pipx binaries
        run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Switch to working directory
        run: cd /home/gh-runner/actions-runner/_work/portfolio/portfolio

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
