name: C++ CI Push Main

on:
  release:
    types: [ published ]
    branches: [ main ]
  push:
    branches: [main]
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  build-and-publish-release:
    runs-on: [self-hosted, Linux, X64, ubuntu-latest-lts]
    if: ${{ github.event_name == 'push' && github.event.pull_request == null }}

    steps:
      - uses: actions/checkout@v4

      - name: Set PATH for pipx binaries
        run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Switch to working directory
        run: cd /home/gh-runner/actions-runner/_work/portfolio/portfolio

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish Executable
        run: |
          sudo systemctl stop portfolio
          sudo rm -r /srv/portfolio/dist
          sudo cp -r /home/gh-runner/actions-runner/_work/portfolio/portfolio/dist /srv/portfolio/
          sudo systemctl start portfolio
