name: C++ CI Push Main

on:
  release:
    types: [ published ]
    branches: [ main ]
  push:
    branches: [main]
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  build-and-publish-release:
    runs-on: [self-hosted, Linux, X64, ubuntu-latest-lts]
    if: ${{ github.event_name == 'push' && github.event.pull_request == null }}

    steps:
      - uses: actions/checkout@v4

      - name: Set PATH for pipx binaries
        run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Load NVM and Node
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use node

      - name: Source environment variables
        run: |
          sudo cp /srv/portfolio/.env ./
          sed -i 's/^PORT=.*/PORT=3300/' .env
          source .env

      - name: Install pnpm
        run: sudo npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish Executable
        run: |
          sudo systemctl stop portfolio
          sudo find /srv/portfolio/ -mindepth 1 ! -name 'media' ! -name '.env' -exec rm -rf {} +
          sudo rsync -av --exclude 'media' --exclude '.env' /home/gh-runner/actions-runner/_work/portfolio/portfolio/ /srv/portfolio/
          sudo systemctl start portfolio
